### ISSUE TITLE
Segmentation fault on Arch Linux ARM v7 after connecting

### ISSUE THREAD

**Issue by Flameborn** [drakkan/sftpgo#249]
I am currently running SFTPGo on a Raspberry Pi 3, on Arch Linux ARM.

My config file is not changed from the defaults. I've added a single user. I am not sure what commit onwards, but I am getting a panic when a client connects and sends a command. (tested with LFTP, Transmit, Total Commander).

My current SFTPGO (sftpgo-git from AUR) version is SFTPGo 1.2.2-dev-4d54949-2020-12-11T12:51:34Z

Here's the log:

```
Dec 14 13:32:30 idris sftpgo[18363]: {"level":"info","time":"2020-12-14T13:32:30.845","sender":"SSH","connection_id":"572d18f74ffd4007bcc1103f581a0d81ba68674b6d0f91ea2be08e753b90a623","message":"User id: 1, logged in with: \"publickey: SHA256:PdoIsEgRStPNkr03AaDdecAItSGhCRIpYNS2Os6kn1I:pi@tardis\", username: \"sfptgouser\", home_dir: \"/mnt/hd/Data\" remote addr: \"192.168.0.1:60708\""}
Dec 14 13:32:31 idris sftpgo[18363]: {"level":"debug","time":"2020-12-14T13:32:31.195","sender":"dataprovider_sqlite","message":"last login updated for user \"sftpgouser\""}
Dec 14 13:32:31 idris sftpgo[18363]: {"level":"debug","time":"2020-12-14T13:32:31.197","sender":"common","connection_id":"572d18f74ffd4007bcc1103f581a0d81ba68674b6d0f91ea2be08e753b90a623","message":"ssh connection added, num open connections: 1"}
Dec 14 13:32:31 idris sftpgo[18363]: {"level":"debug","time":"2020-12-14T13:32:31.200","sender":"SFTP","connection_id":"SFTP_572d18f74ffd4007bcc1103f581a0d81ba68674b6d0f91ea2be08e753b90a623_1","message":"connection added, num open connections: 1"}
Dec 14 13:32:31 idris sftpgo[18363]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 14 13:32:31 idris sftpgo[18363]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x170e0]
Dec 14 13:32:31 idris sftpgo[18363]: goroutine 159 [running]:
Dec 14 13:32:31 idris sftpgo[18363]: github.com/drakkan/sftpgo/common.(*BaseConnection).UpdateLastActivity(0x32e8a00)
Dec 14 13:32:31 idris sftpgo[18363]:         /home/alarm/.cache/yay/sftpgo-git/src/sftpgo/common/connection.go:95 +0xa0
Dec 14 13:32:31 idris sftpgo[18363]: github.com/drakkan/sftpgo/sftpd.(*Connection).Filelist(0x31e72f0, 0x32d6070, 0x32d80a8, 0x24178, 0x32d80a8, 0x228c4)
Dec 14 13:32:31 idris sftpgo[18363]:         /home/alarm/.cache/yay/sftpgo-git/src/sftpgo/sftpd/handler.go:187 +0x24
Dec 14 13:32:31 idris sftpgo[18363]: github.com/pkg/sftp.filestat(0x1197b88, 0x31e72f0, 0x32d6070, 0x119e5f0, 0x309c3f0, 0x1, 0x15c)
Dec 14 13:32:31 idris sftpgo[18363]:         /home/alarm/go/pkg/mod/github.com/pkg/sftp@v1.12.1-0.20201118115123-7230c61342c8/request.go:431 +0x78
Dec 14 13:32:31 idris sftpgo[18363]: github.com/pkg/sftp.(*Request).call(0x32d6070, 0x1197ba0, 0x31e72f0, 0x1197bb8, 0x31e72f0, 0x1197b70, 0x31e72f0, 0x1197b88, 0x31e72f0, 0x119e5f0, ...)
Dec 14 13:32:31 idris sftpgo[18363]:         /home/alarm/go/pkg/mod/github.com/pkg/sftp@v1.12.1-0.20201118115123-7230c61342c8/request.go:220 +0x260
Dec 14 13:32:31 idris sftpgo[18363]: github.com/pkg/sftp.(*RequestServer).packetWorker(0x32d8050, 0x11a5c10, 0x3161da0, 0x3078440, 0x0, 0x0)
Dec 14 13:32:31 idris sftpgo[18363]:         /home/alarm/go/pkg/mod/github.com/pkg/sftp@v1.12.1-0.20201118115123-7230c61342c8/request-server.go:250 +0x444
Dec 14 13:32:31 idris sftpgo[18363]: github.com/pkg/sftp.(*RequestServer).Serve.func2.1(0x32cc390, 0x32d8050, 0x11a5c10, 0x3161da0, 0x3078440)
Dec 14 13:32:31 idris sftpgo[18363]:         /home/alarm/go/pkg/mod/github.com/pkg/sftp@v1.12.1-0.20201118115123-7230c61342c8/request-server.go:153 +0x60
Dec 14 13:32:31 idris sftpgo[18363]: created by github.com/pkg/sftp.(*RequestServer).Serve.func2
Dec 14 13:32:31 idris sftpgo[18363]:         /home/alarm/go/pkg/mod/github.com/pkg/sftp@v1.12.1-0.20201118115123-7230c61342c8/request-server.go:151 +0x7c
Dec 14 13:32:31 idris systemd[1]: sftpgo.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 14 13:32:31 idris systemd[1]: sftpgo.service: Failed with result 'exit-code'.
```

**Comment by Flameborn** [comment]
it turns out that this has been fixed recently, upgrading to a newer git version fixed this issue, so please disregard.

**Comment by drakkan** [comment]
Hi,

this is really strange, I did nothing to fix this issue, it is crashing [here](https://github.com/drakkan/sftpgo/blob/master/common/connection.go#L95), I was thinking about an alignment issue. I don't have a PI to test myself, please let me know if you find other issues, thank you

**Comment by Flameborn** [comment]
That is strange indeed.

Maybe it was a Go issue on ARM, my latest build was via Go 1.15.6, while the previous one was I believe via Go 1.15.2.

**Comment by drakkan** [comment]
Hi, can you please confirm that the last commit works too?

https://github.com/drakkan/sftpgo/commit/ea0bf5e4c80a856ccdf6d37f1f2848418d916479

this way the value accessed atomically should be [64-bit aligned](https://golang.org/pkg/sync/atomic/#pkg-note-BUG)

thank you!

**Comment by Flameborn** [comment]
Hello ☺️

Yes, the latest changes in ea0bf5e work as well.
