### ISSUE TITLE
argon2Params may be accessed before it's initalization.

### ISSUE THREAD

**Issue by clement-buchart** [drakkan/sftpgo#349]
Hello, 

I'm trying to start sftpgo with the data_provider memory by loading a dump file.

Looking at this code :  https://github.com/drakkan/sftpgo/blob/7cfc3f47d51ab9b287e0bcb549f4ffbe16613288/dataprovider/admin.go#L76-L82 
I thought it would work to specify the admin password in clear text in the JSON dump, and that they would be hashed on boot.

This doesn't work though : 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0xa9313a]

goroutine 1 [running]:
github.com/alexedwards/argon2id.CreateHash(0xc00030fbf0, 0x8, 0x0, 0x0, 0x0, 0x0, 0xc00030fbe8)
	/home/runner/go/pkg/mod/github.com/alexedwards/argon2id@v0.0.0-20201228115903-cf543ebc1f7b/argon2id.go:86 +0x3a
github.com/drakkan/sftpgo/dataprovider.(*Admin).validate(0xc0003febe0, 0x0, 0x0)
	/home/runner/work/sftpgo/sftpgo/dataprovider/admin.go:76 +0x787
github.com/drakkan/sftpgo/dataprovider.(*MemoryProvider).addAdmin(0xc000010428, 0xc0003febe0, 0x0, 0x0)
	/home/runner/work/sftpgo/sftpgo/dataprovider/memory.go:367 +0xb8
github.com/drakkan/sftpgo/dataprovider.(*MemoryProvider).restoreAdmins(0xc000010428, 0xc0003fef90, 0x0, 0x0)
	/home/runner/work/sftpgo/sftpgo/dataprovider/memory.go:836 +0x1ba
github.com/drakkan/sftpgo/dataprovider.(*MemoryProvider).reloadConfig(0xc000010428, 0xc0000a6d00, 0x1)
	/home/runner/work/sftpgo/sftpgo/dataprovider/memory.go:816 +0x538
github.com/drakkan/sftpgo/dataprovider.initializeMemoryProvider(0x185e625, 0x1)
	/home/runner/work/sftpgo/sftpgo/dataprovider/memory.go:67 +0x236
github.com/drakkan/sftpgo/dataprovider.createProvider(0x185e625, 0x1, 0x1, 0x1)
	/home/runner/work/sftpgo/sftpgo/dataprovider/dataprovider.go:934 +0x1c5
github.com/drakkan/sftpgo/dataprovider.Initialize(0xc0000435f8, 0x6, 0xc00011e930, 0x64, 0x0, 0x0, 0x1538, 0x0, 0x0, 0x0, ...)
	/home/runner/work/sftpgo/sftpgo/dataprovider/dataprovider.go:472 +0xf5
github.com/drakkan/sftpgo/service.(*Service).Start(0xc000700400, 0x0, 0xc00004c7e0)
	/home/runner/work/sftpgo/sftpgo/service/service.go:104 +0x713
github.com/drakkan/sftpgo/cmd.glob..func6(0x25fa200, 0xc00000fd20, 0x0, 0x2)
	/home/runner/work/sftpgo/sftpgo/cmd/serve.go:38 +0x1c5
github.com/spf13/cobra.(*Command).execute(0x25fa200, 0xc00000fd00, 0x2, 0x2, 0x25fa200, 0xc00000fd00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x25f9f80, 0x0, 0x0, 0x18c1c24)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/drakkan/sftpgo/cmd.Execute()
	/home/runner/work/sftpgo/sftpgo/cmd/root.go:83 +0x31
main.main()
	/home/runner/work/sftpgo/sftpgo/main.go:21 +0xc5
```

I suspect this is because here https://github.com/drakkan/sftpgo/blob/df41f0c556cf360a179198274ed2116829e0e6bc/dataprovider/dataprovider.go#L428-L438
`createProvider` is called before argon2Params is set, but `createProvider` ends up using argon2Params if the password needs re-hashing.

What do you think ? Should I provider a PR moving argon2Params initialization higher ?

**Comment by drakkan** [comment]
Hi,

you are right argon2 should be initialized before `createProvider`. This will only affect `memory` provider. If you can please provide a PR, thank you

**Comment by clement-buchart** [comment]
I'm really sorry I didn't find time to provide the PR, I should have.
Thank you very much for the fix.

**Comment by drakkan** [comment]
No problem, please let me know if you find other issues, thank you
