### ISSUE TITLE
support for exec_command channels

### ISSUE THREAD

**Issue by ysharoiko** [drakkan/sftpgo#803]
Trying to use exec_command in paramiko module with stfpgo 
```SSHConnection.exec_command()```

gives error

```
DEBUG:paramiko.transport:Secsh channel 2 opened.
DEBUG:paramiko.transport:[chan 2] EOF sent (2)
Traceback (most recent call last):
  File "./updatebox.py", line 896, in <module>
    stdin, stdout, stderr = ssh.exec_command("dir")
  File "/usr/local/lib/python3.7/dist-packages/paramiko/client.py", line 514, in exec_command
    chan.exec_command(command)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 72, in _check
    return func(self, *args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 257, in exec_command
    self._wait_for_event()
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 1226, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.
```

is there any support for exec_command channels?
https://github.com/paramiko/paramiko/issues/1444

**Comment by drakkan** [comment]
Hi,

we support the SSH commands documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/ssh-commands.md). You cannot execute any arbitrary system command
